# Site settings
title: Pestles 
description: > # this means to ignore newlines until "baseurl:"
  An opensourced guide book with advice and secret tips 
  to help newgrads navigate the Pes University 
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
